"""rule engine: conditions_json on status_transitions

Revision ID: 0a026bef96c4
Revises: f5a6b7c8d9e0
Create Date: 2026-06-06 14:50:57.902353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a026bef96c4'
down_revision: Union[str, Sequence[str], None] = 'f5a6b7c8d9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_modules_name'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_modules_name'))
        batch_op.create_index(batch_op.f('ix_modules_name'), ['name'], unique=True)

    with op.batch_alter_table('status_transitions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conditions_json', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_transitions', schema=None) as batch_op:
        batch_op.drop_column('conditions_json')

    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_modules_name'))
        batch_op.create_index(batch_op.f('ix_modules_name'), ['name'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_modules_name'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
