"""workflow engine (plan sprint-2/08)

Revision ID: 0b0a96337c3d
Revises: b7c8d9e0f1a2
Create Date: 2026-06-08 18:31:31.155605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.utc_datetime


# revision identifiers, used by Alembic.
revision: str = '0b0a96337c3d'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_trashed', sa.Boolean(), nullable=False),
    sa.Column('draft_definition_json', sa.JSON(), nullable=False),
    sa.Column('current_version_id', sa.String(), nullable=True),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('trigger_entity_type', sa.String(), nullable=True),
    sa.Column('trigger_action', sa.String(), nullable=True),
    sa.Column('next_run_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflows_is_trashed'), ['is_trashed'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_next_run_at'), ['next_run_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_trigger_action'), ['trigger_action'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_trigger_entity_type'), ['trigger_entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflows_trigger_type'), ['trigger_type'], unique=False)

    op.create_table('workflow_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('version_id', sa.String(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by', sa.String(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('definition_snapshot_json', sa.JSON(), nullable=False),
    sa.Column('trigger_payload_json', sa.JSON(), nullable=False),
    sa.Column('triggered_by_run_id', sa.String(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_runs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_workflow_runs_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('published_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_by', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_versions_workflow_id'), ['workflow_id'], unique=False)

    op.create_table('workflow_run_nodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('run_id', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['workflow_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workflow_run_nodes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workflow_run_nodes_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('workflow_run_nodes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_run_nodes_run_id'))

    op.drop_table('workflow_run_nodes')
    with op.batch_alter_table('workflow_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_versions_workflow_id'))

    op.drop_table('workflow_versions')
    with op.batch_alter_table('workflow_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflow_runs_workflow_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_status'))
        batch_op.drop_index(batch_op.f('ix_workflow_runs_created_at'))

    op.drop_table('workflow_runs')
    with op.batch_alter_table('workflows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workflows_trigger_type'))
        batch_op.drop_index(batch_op.f('ix_workflows_trigger_entity_type'))
        batch_op.drop_index(batch_op.f('ix_workflows_trigger_action'))
        batch_op.drop_index(batch_op.f('ix_workflows_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_workflows_next_run_at'))
        batch_op.drop_index(batch_op.f('ix_workflows_is_trashed'))

    op.drop_table('workflows')
    # ### end Alembic commands ###
