"""integration connections + email outbox (plan 09)

Revision ID: 4eb2fa454ce8
Revises: e4f5a6b7c8d9
Create Date: 2026-06-05 11:37:58.044238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4eb2fa454ce8'
down_revision: Union[str, Sequence[str], None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_outbox',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('connection_id', sa.String(), nullable=True),
    sa.Column('to_email', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('html_body', sa.Text(), nullable=False),
    sa.Column('text_body', sa.Text(), nullable=False),
    sa.Column('template_key', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('used_fallback', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_outbox_next_attempt_at'), ['next_attempt_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_outbox_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_outbox_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('connections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('credentials_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'provider', name='uq_connection_tenant_provider')
    )
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_connections_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_connections_tenant_id'), ['tenant_id'], unique=False)

    # (autogen also proposed touching `modules` name index/constraint — pre-
    # existing drift unrelated to this plan; deliberately not included here.)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_connections_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_connections_provider'))

    op.drop_table('connections')
    with op.batch_alter_table('email_outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_outbox_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_email_outbox_status'))
        batch_op.drop_index(batch_op.f('ix_email_outbox_next_attempt_at'))

    op.drop_table('email_outbox')
    # ### end Alembic commands ###
