"""Deferred actions - pending_actions table + tenant_settings grace windows (sprint-4/23 T5)

Revision ID: 65458ac6203e
Revises: run_heartbeat_s4
Create Date: 2026-09-05 04:33:14.021927

The autogenerate pass also picked up unrelated pre-existing drift on this
branch (an `ai_agent_skills` index/unique-constraint change and a
`file_versions` FK re-create) - hand-stripped, out of scope for this slice.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app.models.utc_datetime

# revision identifiers, used by Alembic.
revision: str = '65458ac6203e'
down_revision: Union[str, Sequence[str], None] = 'run_heartbeat_s4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('action_key', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('payload_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('commit_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('requested_by_id', sa.String(), nullable=True),
    sa.Column('error_text', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','committed','cancelled','failed')", name='ck_pending_actions_status'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pending_actions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_pending_actions_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('uq_pending_actions_one_per_record', ['tenant_id', 'entity_type', 'entity_id'], unique=True, postgresql_where=sa.text("status = 'pending'"), sqlite_where=sa.text("status = 'pending'"))

    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deferred_destructive_seconds', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('deferred_reversible_seconds', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenant_settings', schema=None) as batch_op:
        batch_op.drop_column('deferred_reversible_seconds')
        batch_op.drop_column('deferred_destructive_seconds')

    with op.batch_alter_table('pending_actions', schema=None) as batch_op:
        batch_op.drop_index('uq_pending_actions_one_per_record', postgresql_where=sa.text("status = 'pending'"), sqlite_where=sa.text("status = 'pending'"))
        batch_op.drop_index(batch_op.f('ix_pending_actions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_pending_actions_status'))

    op.drop_table('pending_actions')
    # ### end Alembic commands ###
