"""auth_throttle (plan 10)

Revision ID: abbca98c3966
Revises: 4eb2fa454ce8
Create Date: 2026-06-05 15:52:00.607581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abbca98c3966'
down_revision: Union[str, Sequence[str], None] = '4eb2fa454ce8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Brute-force throttle counters (plan 10 §5). The autogenerated
    modules-index churn was dropped - pre-existing drift, not this plan's."""
    op.create_table('auth_throttle',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_auth_throttle_scope_key')
    )
    with op.batch_alter_table('auth_throttle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auth_throttle_key'), ['key'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    with op.batch_alter_table('auth_throttle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auth_throttle_key'))

    op.drop_table('auth_throttle')
