"""workflow run pause/resume columns (plan sprint-4/31 S4, D-A5-20).

Adds ``workflow_runs.paused_node_id`` + ``workflow_runs.resume_state_json`` so a
run can be PARKED (``status = 'waiting'``) at the node that raised
``WorkflowPaused`` and later resumed into the SAME walk. Both nullable, no
backfill needed - no existing row is parked (the ``waiting`` status is new in
this revision).

Revision ID: wf_run_pause_s31
Revises: b7c1d2e3f4a5
Create Date: 2026-09-07
"""
from alembic import op
import sqlalchemy as sa

# House convention for UTCDateTime-bearing autogenerated revisions (none added
# here - kept so the import discipline stays uniform across revisions).
import app.models.utc_datetime  # noqa: F401

revision = "wf_run_pause_s31"
down_revision = "teams_core_s428"  # re-parented at the plan 31 merge (was b7c1d2e3f4a5)
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    cols = {c["name"] for c in inspector.get_columns("workflow_runs")}
    with op.batch_alter_table("workflow_runs") as batch_op:
        if "paused_node_id" not in cols:
            batch_op.add_column(sa.Column("paused_node_id", sa.String(), nullable=True))
        if "resume_state_json" not in cols:
            batch_op.add_column(sa.Column("resume_state_json", sa.JSON(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("workflow_runs") as batch_op:
        batch_op.drop_column("resume_state_json")
        batch_op.drop_column("paused_node_id")
