"""meetings init — the whole ten-table shape in ONE migration.

S0 only writes four of the tables (``user_opt_ins``, ``calendar_events``,
``meetings``, ``meeting_participants``); the transcript / minutes / action-item /
share tables are created empty here so the module has one shape from day one and
S3-S5 add no DDL drip (S0 plan §1).

Explicit DDL, not ``metadata.create_all``: a snapshot built from the live models
is not a snapshot at all - it silently tracks whatever the models say today, so
a later model change leaves no revision behind and drift is undetectable. The
body below was autogenerated against Postgres and is the schema as of rev 1.

Postgres-only DDL; a no-op on the SQLite test engine (per-module Alembic runs
only on Postgres — see ``app/module_platform/migrations.run_module_migrations``).

Revision ID: 0001_meetings_init
Revises:
Create Date: 2026-08-24
"""
import sqlalchemy as sa
from alembic import op

import app.models.utc_datetime

revision = "0001_meetings_init"
down_revision = None
branch_labels = None
depends_on = None

SCHEMA = "app_meetings"


def upgrade() -> None:
    # The version table lives in this schema, so it must exist first.
    op.execute(f'CREATE SCHEMA IF NOT EXISTS "{SCHEMA}"')
    op.create_table('calendar_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('calendar_user_id', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('organiser_email', sa.String(), nullable=True),
    sa.Column('attendees_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('conference_url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('starts_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ends_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.Column('opted_out', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('synced_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'calendar_user_id', 'external_id', name='uq_meetings_event_calendar'),
    schema='app_meetings'
    )
    op.create_index(op.f('ix_app_meetings_calendar_events_calendar_user_id'), 'calendar_events', ['calendar_user_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_calendar_events_tenant_id'), 'calendar_events', ['tenant_id'], unique=False, schema='app_meetings')
    op.create_index('ix_meetings_events_tenant_start', 'calendar_events', ['tenant_id', 'starts_at'], unique=False, schema='app_meetings')
    op.create_table('meetings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('dedupe_key', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('conference_url', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('starts_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ends_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recording_file_id', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('not_admitted_reason', sa.Text(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'dedupe_key', name='uq_meetings_dedupe'),
    schema='app_meetings'
    )
    op.create_index(op.f('ix_app_meetings_meetings_recording_file_id'), 'meetings', ['recording_file_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_meetings_tenant_id'), 'meetings', ['tenant_id'], unique=False, schema='app_meetings')
    op.create_index('ix_meetings_tenant_start', 'meetings', ['tenant_id', 'starts_at'], unique=False, schema='app_meetings')
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('minutes_language', sa.String(), nullable=False),
    sa.Column('audio_retention_days', sa.Integer(), nullable=False),
    sa.Column('llm_connection_id', sa.String(), nullable=True),
    sa.Column('bot_display_name', sa.String(), nullable=True),
    sa.Column('consent_message', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tenant_id'),
    schema='app_meetings'
    )
    op.create_table('user_opt_ins',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sync_token', sa.Text(), nullable=True),
    sa.Column('last_synced_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_meetings_optin_user'),
    schema='app_meetings'
    )
    op.create_index(op.f('ix_app_meetings_user_opt_ins_tenant_id'), 'user_opt_ins', ['tenant_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_user_opt_ins_user_id'), 'user_opt_ins', ['user_id'], unique=False, schema='app_meetings')
    op.create_table('meeting_participants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('is_opted_in', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['app_meetings.meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'email', name='uq_meetings_participant'),
    schema='app_meetings'
    )
    op.create_index(op.f('ix_app_meetings_meeting_participants_meeting_id'), 'meeting_participants', ['meeting_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_meeting_participants_tenant_id'), 'meeting_participants', ['tenant_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_meeting_participants_user_id'), 'meeting_participants', ['user_id'], unique=False, schema='app_meetings')
    op.create_table('minutes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sections_json', sa.JSON(none_as_null=True), nullable=True),
    sa.Column('created_by', sa.String(), nullable=False),
    sa.Column('prompt_version_id', sa.String(), nullable=True),
    sa.Column('llm_provider', sa.String(), nullable=True),
    sa.Column('llm_model', sa.String(), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['app_meetings.meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'version', name='uq_meetings_minutes_version'),
    schema='app_meetings'
    )
    op.create_index(op.f('ix_app_meetings_minutes_meeting_id'), 'minutes', ['meeting_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_minutes_tenant_id'), 'minutes', ['tenant_id'], unique=False, schema='app_meetings')
    op.create_table('shares',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('shared_by', sa.String(), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['app_meetings.meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_meetings_share'),
    schema='app_meetings'
    )
    op.create_index(op.f('ix_app_meetings_shares_meeting_id'), 'shares', ['meeting_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_shares_tenant_id'), 'shares', ['tenant_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_shares_user_id'), 'shares', ['user_id'], unique=False, schema='app_meetings')
    op.create_table('transcripts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('stt_provider', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['app_meetings.meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', name='uq_meetings_transcript_meeting'),
    schema='app_meetings'
    )
    op.create_index(op.f('ix_app_meetings_transcripts_meeting_id'), 'transcripts', ['meeting_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_transcripts_tenant_id'), 'transcripts', ['tenant_id'], unique=False, schema='app_meetings')
    op.create_table('action_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('minutes_id', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('owner_email', sa.String(), nullable=True),
    sa.Column('due_on', sa.Date(), nullable=True),
    sa.Column('done_at', app.models.utc_datetime.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['minutes_id'], ['app_meetings.minutes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_meetings'
    )
    op.create_index(op.f('ix_app_meetings_action_items_minutes_id'), 'action_items', ['minutes_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_action_items_tenant_id'), 'action_items', ['tenant_id'], unique=False, schema='app_meetings')
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('transcript_id', sa.String(), nullable=False),
    sa.Column('speaker', sa.String(), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', app.models.utc_datetime.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transcript_id'], ['app_meetings.transcripts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='app_meetings'
    )
    op.create_index(op.f('ix_app_meetings_transcript_segments_tenant_id'), 'transcript_segments', ['tenant_id'], unique=False, schema='app_meetings')
    op.create_index(op.f('ix_app_meetings_transcript_segments_transcript_id'), 'transcript_segments', ['transcript_id'], unique=False, schema='app_meetings')
    op.create_index('ix_meetings_segments_transcript_start', 'transcript_segments', ['transcript_id', 'start_ms'], unique=False, schema='app_meetings')
    # Transcript search is pg_trgm text-similarity (spine M19) — no SQLAlchemy
    # equivalent, so it is declared here rather than in models.py.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.execute(
        f"CREATE INDEX IF NOT EXISTS ix_meetings_segments_text_trgm "
        f'ON "{SCHEMA}".transcript_segments USING gin (text gin_trgm_ops)'
    )


def downgrade() -> None:
    op.execute(f'DROP INDEX IF EXISTS "{SCHEMA}".ix_meetings_segments_text_trgm')
    op.drop_index('ix_meetings_segments_transcript_start', table_name='transcript_segments', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_transcript_segments_transcript_id'), table_name='transcript_segments', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_transcript_segments_tenant_id'), table_name='transcript_segments', schema='app_meetings')
    op.drop_table('transcript_segments', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_action_items_tenant_id'), table_name='action_items', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_action_items_minutes_id'), table_name='action_items', schema='app_meetings')
    op.drop_table('action_items', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_transcripts_tenant_id'), table_name='transcripts', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_transcripts_meeting_id'), table_name='transcripts', schema='app_meetings')
    op.drop_table('transcripts', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_shares_user_id'), table_name='shares', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_shares_tenant_id'), table_name='shares', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_shares_meeting_id'), table_name='shares', schema='app_meetings')
    op.drop_table('shares', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_minutes_tenant_id'), table_name='minutes', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_minutes_meeting_id'), table_name='minutes', schema='app_meetings')
    op.drop_table('minutes', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_meeting_participants_user_id'), table_name='meeting_participants', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_meeting_participants_tenant_id'), table_name='meeting_participants', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_meeting_participants_meeting_id'), table_name='meeting_participants', schema='app_meetings')
    op.drop_table('meeting_participants', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_user_opt_ins_user_id'), table_name='user_opt_ins', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_user_opt_ins_tenant_id'), table_name='user_opt_ins', schema='app_meetings')
    op.drop_table('user_opt_ins', schema='app_meetings')
    op.drop_table('tenant_settings', schema='app_meetings')
    op.drop_index('ix_meetings_tenant_start', table_name='meetings', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_meetings_tenant_id'), table_name='meetings', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_meetings_recording_file_id'), table_name='meetings', schema='app_meetings')
    op.drop_table('meetings', schema='app_meetings')
    op.drop_index('ix_meetings_events_tenant_start', table_name='calendar_events', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_calendar_events_tenant_id'), table_name='calendar_events', schema='app_meetings')
    op.drop_index(op.f('ix_app_meetings_calendar_events_calendar_user_id'), table_name='calendar_events', schema='app_meetings')
    op.drop_table('calendar_events', schema='app_meetings')
