/**
 * AC-DLA-69 - Playwright is retired from this repo (user ruling 2026-09-04,
 * plan 23 D15: "I strongly don't want to use any or see any playwright in the
 * repo anymore"). Browser verification is the `agent-browser` CLI only.
 *
 * This test walks the whole repo from its root (the parent of
 * `service_frontend/`) and fails, listing every `file:line`, on any
 * case-insensitive occurrence of the word "playwright" outside the excluded
 * paths below.
 *
 * Excluded paths and why:
 * - `node_modules`, `.next`, `.git`, `.claude/worktrees` - generated/vendored/
 *   sibling-worktree trees, not this repo's authored content.
 * - `documentation/plans` - historical plan + acceptance-criteria + test-report
 *   records (AC-DLA-69: "historical plans and test reports are records and
 *   stay verbatim").
 * - `documentation/preliminary_planning` - the project's pre-repo founding
 *   planning documents (10-week execution timeline, project plan), written
 *   before this repo's process existed. Same "historical record" class as
 *   `documentation/plans` - rewriting them to describe today's tooling would
 *   misrepresent history, not correct it.
 * - `service_backend/modules/meetings/bot` - a shipped product feature (a
 *   Google Meet-joining bot) that genuinely depends on the `playwright` PyPI
 *   package as its headless-browser automation engine. This is unrelated to
 *   the repo's own browser-verification tooling being retired; removing or
 *   renaming it would break a real feature, not scrub a stale reference.
 * - `service_frontend/package-lock.json` - auto-generated by npm. After
 *   `npm uninstall @playwright/test --package-lock-only` the only remaining
 *   occurrence is Next.js's own `peerDependencies`/`peerDependenciesMeta`
 *   entry for `@playwright/test` (optional, declared by the `next` package
 *   itself) - upstream metadata this repo does not author and cannot edit
 *   without corrupting the lockfile.
 * - `*.tsbuildinfo` - gitignored TypeScript incremental-build caches. They
 *   list every resolved module path on disk; as long as the shared
 *   `node_modules` (a symlink, never rewritten by this slice) still
 *   physically contains the `@playwright/test` package, a fresh `tsc` run
 *   can transiently re-mention it here. Generated, not authored, not
 *   committed.
 * - AGENTS.md (symlinked as CLAUDE.md) and PRINCIPLES.md - each keeps EXACTLY
 *   ONE sentence stating Playwright is retired (D15) so future readers know
 *   why the tooling changed; asserted below by name+count instead of a blanket
 *   skip, so a second mention anywhere else in either file still fails.
 * - This file itself - it necessarily discusses the word it guards against.
 * - Symlinks (e.g. `CLAUDE.md -> AGENTS.md`) are not walked as their own
 *   entry, so a symlinked alias never double-counts its target's content.
 */
import { describe, expect, it } from 'vitest';
import { lstatSync, readFileSync, readdirSync } from 'node:fs';
import { join, relative } from 'node:path';

const REPO_ROOT = join(__dirname, '..');
const MAX_FILE_BYTES = 2 * 1024 * 1024; // 2 MB

const SKIP_DIR_NAMES = new Set(['node_modules', '.next', '.git']);

// Repo-relative directory paths (posix-style) skipped entirely.
const SKIP_DIR_PATHS = [
  '.claude/worktrees',
  'documentation/plans',
  'documentation/preliminary_planning',
  'service_backend/modules/meetings/bot',
];

// Repo-relative file paths skipped entirely (see file-level comment above).
const SKIP_FILE_PATHS = new Set([
  'service_frontend/package-lock.json',
  'service_frontend/no-playwright.guard.test.ts',
]);

// Files allowed to keep exactly one Playwright-is-retired sentence.
const RETIREMENT_SENTENCE_ALLOWANCE: Record<string, number> = {
  'AGENTS.md': 1,
  'PRINCIPLES.md': 1,
};

const BINARY_EXTENSIONS = new Set([
  '.png',
  '.jpg',
  '.jpeg',
  '.gif',
  '.webp',
  '.ico',
  '.pdf',
  '.woff',
  '.woff2',
  '.ttf',
  '.eot',
  '.otf',
  '.zip',
  '.gz',
  '.tar',
  '.mp4',
  '.mp3',
  '.wav',
  '.svg',
]);

// Generated caches, not authored source (see file-level comment above).
const SKIPPED_EXTENSIONS = new Set(['.tsbuildinfo']);

function isSkippedDir(relPath: string): boolean {
  return SKIP_DIR_PATHS.some((skip) => relPath === skip || relPath.startsWith(`${skip}/`));
}

function isSkippedExtension(fileName: string): boolean {
  const dot = fileName.lastIndexOf('.');
  if (dot === -1) return false;
  const ext = fileName.slice(dot).toLowerCase();
  return BINARY_EXTENSIONS.has(ext) || SKIPPED_EXTENSIONS.has(ext);
}

function collectFiles(dir: string, acc: string[]): void {
  let entries: string[];
  try {
    entries = readdirSync(dir);
  } catch {
    return;
  }
  for (const entry of entries) {
    const abs = join(dir, entry);
    const rel = relative(REPO_ROOT, abs).split('\\').join('/');
    let st;
    try {
      st = lstatSync(abs);
    } catch {
      continue;
    }
    if (st.isSymbolicLink()) continue;
    if (st.isDirectory()) {
      if (SKIP_DIR_NAMES.has(entry)) continue;
      if (isSkippedDir(rel)) continue;
      collectFiles(abs, acc);
    } else if (st.isFile()) {
      if (SKIP_FILE_PATHS.has(rel)) continue;
      if (isSkippedExtension(entry)) continue;
      if (st.size > MAX_FILE_BYTES) continue;
      acc.push(abs);
    }
  }
}

describe('AC-DLA-69: no Playwright anywhere outside historical records', () => {
  it('has zero case-insensitive "playwright" occurrences outside the documented exceptions', () => {
    const files: string[] = [];
    collectFiles(REPO_ROOT, files);

    const hits: string[] = [];
    const retirementCounts: Record<string, number> = {};

    for (const abs of files) {
      const rel = relative(REPO_ROOT, abs).split('\\').join('/');
      let content: string;
      try {
        content = readFileSync(abs, 'utf8');
      } catch {
        continue; // unreadable as text - not a source file we scrub
      }
      // Skip content that looks binary despite the extension allowlist above.
      if (content.includes('\u0000')) continue;

      const lines = content.split('\n');
      lines.forEach((line, idx) => {
        if (!/playwright/i.test(line)) return;
        if (RETIREMENT_SENTENCE_ALLOWANCE[rel] !== undefined) {
          retirementCounts[rel] = (retirementCounts[rel] ?? 0) + 1;
          return;
        }
        hits.push(`${rel}:${idx + 1}: ${line.trim()}`);
      });
    }

    if (hits.length > 0) {
      throw new Error(
        `Found ${hits.length} live "playwright" occurrence(s) outside documentation/plans/**, ` +
          `documentation/preliminary_planning/**, service_backend/modules/meetings/bot/**, and ` +
          `service_frontend/package-lock.json:\n${hits.join('\n')}`
      );
    }

    for (const [file, allowed] of Object.entries(RETIREMENT_SENTENCE_ALLOWANCE)) {
      const found = retirementCounts[file] ?? 0;
      expect(found, `${file} should keep exactly ${allowed} "Playwright is retired" sentence`).toBe(
        allowed
      );
    }
  });
});
