// @vitest-environment node
/**
 * AC-DLA-69 - Playwright is retired from this repo (user ruling 2026-09-04,
 * plan 23 D15: "I strongly don't want to use any or see any playwright in the
 * repo anymore"). Browser verification is the `agent-browser` CLI only.
 *
 * Rewritten in the T0 review round 1 fix: this is now a single `git grep`
 * call over TRACKED files (`git ls-files` is what decides scope - gitignored
 * artefacts on a developer's disk, and any local untracked state, never
 * decide the verdict), not a filesystem walk. No 2MB cap, no swallowed
 * errors, no jsdom (`@vitest-environment node` above - this test never
 * touches the DOM).
 *
 * Named exclusions (pathspecs on the `git grep` call) and why:
 * - `documentation/plans` - historical plan + acceptance-criteria + test-report
 *   records (AC-DLA-69: "historical plans and test reports are records and
 *   stay verbatim").
 * - `documentation/preliminary_planning` - the project's pre-repo founding
 *   planning documents, written before this repo's process existed. Same
 *   "historical record" class as `documentation/plans`.
 * - `service_backend/modules/meetings/bot` - a shipped product feature (a
 *   Google Meet-joining bot) that genuinely depends on the `playwright` PyPI
 *   package as its headless-browser automation engine. Unrelated to this
 *   repo's own browser-verification tooling being retired.
 * - `service_frontend/package-lock.json` - auto-generated by npm; the only
 *   remaining occurrence is Next.js's own optional `@playwright/test`
 *   peerDependency metadata, upstream content this repo does not author.
 *
 * Two further, code-level exclusions (not pathspecs, so they still get
 * scanned and any OTHER hit inside them still fails the test):
 * - AGENTS.md (symlinked as CLAUDE.md) and PRINCIPLES.md each keep AT MOST
 *   ONE line stating Playwright is retired (D15) so future readers know why;
 *   `RETIREMENT_LINE_ALLOWANCE` below.
 * - This file itself - it necessarily discusses the word it guards against,
 *   and its own tracked filename contains "playwright" (see the `git
 *   ls-files` check below).
 */
import { describe, expect, it } from 'vitest';
import { execFileSync } from 'node:child_process';

const THIS_FILE = 'service_frontend/no-playwright.guard.test.ts';

const EXCLUDED_PATHSPECS = [
  '.',
  ':!documentation/plans',
  ':!documentation/preliminary_planning',
  ':!service_backend/modules/meetings/bot',
  ':!service_frontend/package-lock.json',
];

// Files allowed to keep AT MOST one line naming Playwright as retired.
const RETIREMENT_LINE_ALLOWANCE: Record<string, number> = {
  'AGENTS.md': 1,
  'PRINCIPLES.md': 1,
};

function repoRoot(): string {
  try {
    return execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim();
  } catch (err) {
    throw new Error(
      `AC-DLA-69 guard: 'git rev-parse --show-toplevel' failed - this must run inside a git ` +
        `repository (no other way to find the tracked-file root). Underlying error: ${err}`
    );
  }
}

/** Runs `git grep -Iin playwright -- <pathspecs>` once. git grep exits 1 (not
 * an error) when there are zero matches - only other exit codes are real
 * failures and must fail the test loudly rather than being swallowed. */
function gitGrepPlaywright(cwd: string): string[] {
  try {
    const out = execFileSync(
      'git',
      ['grep', '-Iin', 'playwright', '--', ...EXCLUDED_PATHSPECS],
      { cwd, encoding: 'utf8' }
    );
    return out.split('\n').filter(Boolean);
  } catch (err) {
    const status = (err as { status?: number }).status;
    if (status === 1) return []; // zero matches - a valid, good outcome
    throw new Error(`AC-DLA-69 guard: 'git grep' failed unexpectedly (status ${status}): ${err}`);
  }
}

function gitLsFilesPlaywright(cwd: string): string[] {
  let files: string[];
  try {
    files = execFileSync('git', ['ls-files'], { cwd, encoding: 'utf8' }).split('\n').filter(Boolean);
  } catch (err) {
    throw new Error(`AC-DLA-69 guard: 'git ls-files' failed unexpectedly: ${err}`);
  }
  return files.filter((f) => f !== THIS_FILE && /playwright/i.test(f));
}

describe('AC-DLA-69: no Playwright anywhere outside the named exclusions', () => {
  it('has zero case-insensitive "playwright" occurrences in tracked content, and no tracked path names it', () => {
    const root = repoRoot();

    const lines = gitGrepPlaywright(root); // "path:lineNo:content"
    const byFile = new Map<string, string[]>();
    for (const line of lines) {
      const idx = line.indexOf(':');
      const file = line.slice(0, idx);
      const rest = line.slice(idx + 1);
      if (file === THIS_FILE) continue; // this file necessarily discusses the word
      if (!byFile.has(file)) byFile.set(file, []);
      byFile.get(file)!.push(rest);
    }

    const disallowedFiles = [...byFile.keys()].filter(
      (f) => RETIREMENT_LINE_ALLOWANCE[f] === undefined
    );
    if (disallowedFiles.length > 0) {
      const detail = disallowedFiles
        .map((f) => byFile.get(f)!.map((l) => `${f}:${l}`).join('\n'))
        .join('\n');
      throw new Error(`Found live "playwright" occurrence(s) outside the named exclusions:\n${detail}`);
    }

    for (const [file, allowed] of Object.entries(RETIREMENT_LINE_ALLOWANCE)) {
      const found = byFile.get(file)?.length ?? 0;
      expect(found, `${file} should carry at most ${allowed} Playwright-is-retired line`).toBeLessThanOrEqual(
        allowed
      );
    }

    const namedPaths = gitLsFilesPlaywright(root);
    expect(namedPaths, `tracked path name(s) still contain "playwright": ${namedPaths.join(', ')}`).toEqual(
      []
    );
  });
});
