/**
 * Frontend node catalog (plan sprint-2/08 D8, fanned out in sprint-2/09 D7/D8)
 * - mirror of the backend `app/workflow_engine/registry.py` TriggerDef/
 * ActionDef. Drives the palette, the config drawer (field schema), and the
 * dynamic-content picker (output schema). The entity triggers expose dynamic
 * `trigger.record.*` outputs resolved from the chosen entity's metadata (the
 * drawer injects them - the catalog lists only the static seed).
 */
import type {
  ActionCatalogEntry,
  IfCatalogEntry,
  NodeCatalogEntry,
  TriggerCatalogEntry,
} from '@/types/workflows';

/** Output seed shared by every entity trigger (record id + actor + action).
 * The chosen entity's fields are appended as `trigger.record.<field>` live. */
const ENTITY_TRIGGER_OUTPUTS = [
  { key: 'trigger.record.id', label: 'Record · id' },
  { key: 'trigger.action', label: 'Action' },
  { key: 'trigger.actor.name', label: 'Actor name' },
  { key: 'trigger.actor.email', label: 'Actor email' },
];

/** Output seed shared by every omnichannel contact-scoped trigger (plan 31
 * §5.2) - the contact, the conversation and the workspace it happened in. */
const OMNICHANNEL_CONTACT_TRIGGER_OUTPUTS = [
  { key: 'trigger.contact.id', label: 'Contact · id' },
  { key: 'trigger.contact.name', label: 'Contact · name' },
  { key: 'trigger.contact.phone', label: 'Contact · phone' },
  { key: 'trigger.conversationId', label: 'Conversation id' },
  { key: 'trigger.workspaceId', label: 'Workspace id' },
  { key: 'trigger.actor.name', label: 'Actor name' },
  { key: 'trigger.actor.email', label: 'Actor email' },
];

/** The "trigger once per contact" flag every plan-31 contact trigger offers
 * (D-A5-4) - a labelled checkbox, not a `select`, matching the existing
 * boolean-flag convention (OutputParamsEditor's Required/Stateful rows). */
const TRIGGER_ONCE_PER_CONTACT_FIELD = {
  key: 'triggerOncePerContact',
  label: 'Trigger once per contact',
  type: 'boolean' as const,
};

export const TRIGGER_CATALOG: TriggerCatalogEntry[] = [
  {
    kind: 'trigger',
    type: 'manual',
    label: 'Manual',
    description: 'Run on demand from a button (with optional inputs).',
    icon: 'MousePointerClick',
    category: 'Triggers',
    fields: [
      {
        key: 'inputs',
        label: 'Run inputs',
        type: 'inputs',
      },
    ],
    // Manual inputs append `trigger.input.<key>` dynamically (resolved by the
    // picker from the node config); the static seed is the run metadata.
    outputs: [
      { key: 'trigger.triggeredBy', label: 'Triggered by' },
      { key: 'trigger.actor.name', label: 'Actor name' },
      { key: 'trigger.actor.email', label: 'Actor email' },
    ],
  },
  {
    kind: 'trigger',
    type: 'entity.created',
    label: 'Record created',
    description: 'Fires when a record of the chosen entity is created.',
    icon: 'FilePlus2',
    category: 'Triggers',
    fields: [{ key: 'entityType', label: 'Entity', type: 'entity', required: true }],
    outputs: ENTITY_TRIGGER_OUTPUTS,
  },
  {
    kind: 'trigger',
    type: 'entity.updated',
    label: 'Record updated',
    description: 'Fires when a record of the chosen entity is updated.',
    icon: 'FilePenLine',
    category: 'Triggers',
    fields: [{ key: 'entityType', label: 'Entity', type: 'entity', required: true }],
    outputs: [...ENTITY_TRIGGER_OUTPUTS, { key: 'trigger.changedFields', label: 'Changed fields' }],
  },
  {
    kind: 'trigger',
    type: 'entity.deleted',
    label: 'Record deleted',
    description: 'Fires when a record of the chosen entity is deleted.',
    icon: 'FileX',
    category: 'Triggers',
    fields: [{ key: 'entityType', label: 'Entity', type: 'entity', required: true }],
    outputs: ENTITY_TRIGGER_OUTPUTS,
  },
  {
    kind: 'trigger',
    type: 'entity.field_changed',
    label: 'Field changed',
    description: 'Fires when a specific field on the chosen entity changes.',
    icon: 'PencilLine',
    category: 'Triggers',
    fields: [
      { key: 'entityType', label: 'Entity', type: 'entity', required: true },
      { key: 'field', label: 'Field', type: 'field', required: true },
    ],
    outputs: [...ENTITY_TRIGGER_OUTPUTS, { key: 'trigger.changedFields', label: 'Changed fields' }],
  },
  {
    kind: 'trigger',
    type: 'entity.status_changed',
    label: 'Status changed',
    description: 'Fires when the chosen entity moves between statuses.',
    icon: 'Activity',
    category: 'Triggers',
    fields: [
      { key: 'entityType', label: 'Entity', type: 'entity', required: true, entityFilter: 'status' },
      { key: 'fromStatus', label: 'From status', type: 'status' },
      { key: 'toStatus', label: 'To status', type: 'status' },
    ],
    outputs: [
      { key: 'trigger.record.id', label: 'Record · id' },
      { key: 'trigger.fromStatus', label: 'From status' },
      { key: 'trigger.toStatus', label: 'To status' },
      { key: 'trigger.actor.name', label: 'Actor name' },
    ],
  },
  {
    kind: 'trigger',
    type: 'entity.shortcut',
    label: 'Shortcut',
    description: 'Fires when an agent runs this workflow as a shortcut on a record.',
    icon: 'Zap',
    category: 'Triggers',
    fields: [
      { key: 'entityType', label: 'Entity', type: 'entity', required: true, entityFilter: 'shortcut' },
    ],
    outputs: ENTITY_TRIGGER_OUTPUTS,
  },
  {
    kind: 'trigger',
    type: 'schedule.cron',
    label: 'Schedule',
    description: 'Runs on a recurring schedule in a chosen timezone.',
    icon: 'CalendarClock',
    category: 'Triggers',
    fields: [{ key: 'cron', label: 'Runs', type: 'cron', required: true }],
    outputs: [{ key: 'trigger.firedAt', label: 'Fired at' }],
  },
  {
    kind: 'trigger',
    type: 'form.submitted',
    label: 'Form submitted',
    description: 'Fires when a chosen form receives a submission.',
    icon: 'ClipboardCheck',
    category: 'Triggers',
    fields: [{ key: 'formId', label: 'Form', type: 'form', required: true }],
    // `trigger.answers.<key>` outputs are dynamic per selected form (resolved by
    // the picker from the workflow metadata); the static seed is the run meta.
    outputs: [
      { key: 'trigger.formId', label: 'Form id' },
      { key: 'trigger.submissionId', label: 'Submission id' },
    ],
  },
  {
    kind: 'trigger',
    type: 'omnichannel.message_received',
    label: 'Incoming omnichannel message',
    description: 'Fires when a WhatsApp message arrives on a chosen channel (or any channel).',
    icon: 'MessageCircle',
    category: 'Triggers',
    module: 'omnichannel',
    fields: [{ key: 'channelId', label: 'Channel', type: 'omnichannelChannel' }],
    outputs: [
      { key: 'trigger.message.id', label: 'Message · id' },
      { key: 'trigger.message.text', label: 'Message · text' },
      { key: 'trigger.message.type', label: 'Message · type' },
      { key: 'trigger.message.mediaUrl', label: 'Message · media URL' },
      { key: 'trigger.contact.id', label: 'Contact · id' },
      { key: 'trigger.contact.name', label: 'Contact · name' },
      { key: 'trigger.contact.phone', label: 'Contact · phone' },
      { key: 'trigger.channel.id', label: 'Channel · id' },
      { key: 'trigger.channel.name', label: 'Channel · name' },
      { key: 'trigger.conversationId', label: 'Conversation id' },
    ],
  },
  // ---- plan 31 (omnichannel workflow parity) - conversation/contact triggers ----
  {
    kind: 'trigger',
    type: 'omnichannel.conversation_opened',
    label: 'Conversation opened',
    description: 'Fires when a conversation moves to open (first contact or a reopen).',
    icon: 'FolderOpen',
    category: 'Triggers',
    module: 'omnichannel',
    fields: [
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace' },
      { key: 'channelId', label: 'Channel', type: 'omnichannelChannel' },
      { key: 'reopenOnly', label: 'Only on reopen', type: 'boolean' },
      TRIGGER_ONCE_PER_CONTACT_FIELD,
    ],
    outputs: [
      ...OMNICHANNEL_CONTACT_TRIGGER_OUTPUTS,
      { key: 'trigger.isReopen', label: 'Is reopen' },
      { key: 'trigger.channelId', label: 'Channel id' },
    ],
  },
  {
    kind: 'trigger',
    type: 'omnichannel.conversation_closed',
    label: 'Conversation closed',
    description: 'Fires when a conversation is closed, optionally for one close reason.',
    icon: 'FolderX',
    category: 'Triggers',
    module: 'omnichannel',
    fields: [
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace' },
      { key: 'closeReasonId', label: 'Close reason', type: 'omnichannelCloseReason' },
      TRIGGER_ONCE_PER_CONTACT_FIELD,
    ],
    outputs: [
      ...OMNICHANNEL_CONTACT_TRIGGER_OUTPUTS,
      { key: 'trigger.closeReasonId', label: 'Close reason id' },
      { key: 'trigger.closeReasonLabel', label: 'Close reason' },
      { key: 'trigger.note', label: 'Note' },
    ],
  },
  {
    kind: 'trigger',
    type: 'omnichannel.conversation_assigned',
    label: 'Conversation assigned',
    description: 'Fires when a conversation is assigned, reassigned, or unassigned.',
    icon: 'UserCheck',
    category: 'Triggers',
    module: 'omnichannel',
    fields: [
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace' },
      { key: 'assigneeUserId', label: 'Assignee', type: 'omnichannelMember' },
      { key: 'onUnassign', label: 'Only on unassign', type: 'boolean' },
      TRIGGER_ONCE_PER_CONTACT_FIELD,
    ],
    outputs: [
      ...OMNICHANNEL_CONTACT_TRIGGER_OUTPUTS,
      { key: 'trigger.assigneeUserId', label: 'Assignee id' },
      { key: 'trigger.previousAssigneeUserId', label: 'Previous assignee id' },
      { key: 'trigger.assignedVia', label: 'Assigned via' },
    ],
  },
  {
    kind: 'trigger',
    type: 'omnichannel.contact_tag_added',
    label: 'Contact tag added',
    description: 'Fires when a tag is added to a contact, optionally for one tag.',
    icon: 'Tag',
    category: 'Triggers',
    module: 'omnichannel',
    fields: [
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace' },
      { key: 'tagId', label: 'Tag', type: 'omnichannelTag' },
      TRIGGER_ONCE_PER_CONTACT_FIELD,
    ],
    outputs: [
      ...OMNICHANNEL_CONTACT_TRIGGER_OUTPUTS,
      { key: 'trigger.tagId', label: 'Tag id' },
      { key: 'trigger.tagName', label: 'Tag name' },
    ],
  },
  {
    kind: 'trigger',
    type: 'omnichannel.contact_tag_removed',
    label: 'Contact tag removed',
    description: 'Fires when a tag is removed from a contact, optionally for one tag.',
    icon: 'Tag',
    category: 'Triggers',
    module: 'omnichannel',
    fields: [
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace' },
      { key: 'tagId', label: 'Tag', type: 'omnichannelTag' },
      TRIGGER_ONCE_PER_CONTACT_FIELD,
    ],
    outputs: [
      ...OMNICHANNEL_CONTACT_TRIGGER_OUTPUTS,
      { key: 'trigger.tagId', label: 'Tag id' },
      { key: 'trigger.tagName', label: 'Tag name' },
    ],
  },
  {
    kind: 'trigger',
    type: 'omnichannel.contact_field_changed',
    label: 'Contact field updated',
    description: 'Fires when a registered custom field on a contact changes.',
    icon: 'PencilLine',
    category: 'Triggers',
    module: 'omnichannel',
    fields: [
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace' },
      { key: 'fieldKey', label: 'Field', type: 'omnichannelContactField', required: true },
      { key: 'newValue', label: 'New value', type: 'text' },
      TRIGGER_ONCE_PER_CONTACT_FIELD,
    ],
    outputs: [
      ...OMNICHANNEL_CONTACT_TRIGGER_OUTPUTS,
      { key: 'trigger.fieldKey', label: 'Field key' },
      { key: 'trigger.fromValue', label: 'From value' },
      { key: 'trigger.toValue', label: 'To value' },
    ],
  },
  {
    kind: 'trigger',
    type: 'omnichannel.lifecycle_changed',
    label: 'Lifecycle updated',
    description: 'Fires when a contact moves between lifecycle stages.',
    icon: 'Activity',
    category: 'Triggers',
    module: 'omnichannel',
    fields: [
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace' },
      { key: 'fromStageId', label: 'From stage', type: 'omnichannelLifecycleStage' },
      { key: 'toStageId', label: 'To stage', type: 'omnichannelLifecycleStage' },
      TRIGGER_ONCE_PER_CONTACT_FIELD,
    ],
    outputs: [
      ...OMNICHANNEL_CONTACT_TRIGGER_OUTPUTS,
      { key: 'trigger.fromStatus', label: 'From stage' },
      { key: 'trigger.toStatus', label: 'To stage' },
      { key: 'trigger.toStageLabel', label: 'To stage label' },
    ],
  },
  {
    kind: 'trigger',
    type: 'omnichannel.broadcast_completed',
    label: 'Broadcast completed',
    description: 'Fires when a broadcast finishes sending.',
    icon: 'Megaphone',
    category: 'Triggers',
    module: 'omnichannel',
    fields: [{ key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace' }],
    outputs: [
      { key: 'trigger.broadcastId', label: 'Broadcast id' },
      { key: 'trigger.broadcastName', label: 'Broadcast name' },
      { key: 'trigger.sent', label: 'Sent count' },
      { key: 'trigger.failed', label: 'Failed count' },
    ],
  },
];

export const ACTION_CATALOG: ActionCatalogEntry[] = [
  {
    kind: 'action',
    type: 'email.send',
    label: 'Send email',
    description: 'Render a template and enqueue it to the outbox.',
    icon: 'Mail',
    category: 'Actions',
    requiresConnection: 'email',
    fields: [
      {
        key: 'mode',
        label: 'Email type',
        type: 'select',
        options: [
          { value: 'template', label: 'Use a template' },
          { value: 'custom', label: 'Write a custom email' },
        ],
      },
      {
        key: 'templateId',
        label: 'Template',
        type: 'template',
        required: true,
        showWhen: { field: 'mode', value: 'template' },
      },
      {
        key: 'subject',
        label: 'Subject',
        type: 'text',
        required: true,
        mergeable: true,
        showWhen: { field: 'mode', value: 'custom' },
      },
      {
        key: 'body',
        label: 'Body',
        type: 'textarea',
        required: true,
        mergeable: true,
        showWhen: { field: 'mode', value: 'custom' },
      },
      {
        key: 'to',
        label: 'To',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.input.email }}',
      },
      {
        key: 'subjectOverride',
        label: 'Subject override',
        type: 'text',
        mergeable: true,
        showWhen: { field: 'mode', value: 'template' },
      },
    ],
    outputs: [
      { key: 'messageId', label: 'Message id' },
      { key: 'status', label: 'Enqueue status' },
    ],
  },
  {
    kind: 'action',
    type: 'storage.put',
    label: 'Store a file',
    description: 'Write content to storage and output its URL + metadata.',
    icon: 'HardDriveUpload',
    category: 'Actions',
    requiresConnection: 'storage',
    fields: [
      {
        key: 'key',
        label: 'Storage key',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: 'reports/{{ trigger.record.id }}.txt',
      },
      { key: 'content', label: 'Content', type: 'textarea', required: true, mergeable: true },
    ],
    outputs: [
      { key: 'url', label: 'URL' },
      { key: 'key', label: 'Key' },
      { key: 'size', label: 'Size (bytes)' },
      { key: 'mime', label: 'MIME type' },
    ],
  },
  {
    kind: 'action',
    type: 'storage.get',
    label: 'Resolve a file',
    description: 'Resolve a stored key to a URL + metadata (no bytes loaded).',
    icon: 'HardDriveDownload',
    category: 'Actions',
    requiresConnection: 'storage',
    fields: [
      { key: 'key', label: 'Storage key', type: 'text', required: true, mergeable: true },
    ],
    outputs: [
      { key: 'url', label: 'URL' },
      { key: 'size', label: 'Size (bytes)' },
      { key: 'mime', label: 'MIME type' },
    ],
  },
  {
    kind: 'action',
    type: 'storage.delete',
    label: 'Delete a file',
    description: 'Permanently delete a stored object by key.',
    icon: 'Trash2',
    category: 'Actions',
    requiresConnection: 'storage',
    destructive: true,
    fields: [
      { key: 'key', label: 'Storage key', type: 'text', required: true, mergeable: true },
    ],
    outputs: [{ key: 'deleted', label: 'Deleted' }],
  },
  {
    kind: 'action',
    type: 'entity.transition_status',
    label: 'Change status',
    description: "Move a record to a status through its state machine.",
    icon: 'ArrowLeftRight',
    category: 'Actions',
    destructive: true,
    fields: [
      { key: 'entityType', label: 'Entity', type: 'entity', required: true, entityFilter: 'status' },
      {
        key: 'recordId',
        label: 'Record',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.record.id }}',
      },
      { key: 'toStatus', label: 'Move to status', type: 'status', required: true },
    ],
    outputs: [
      { key: 'status', label: 'New status' },
      { key: 'recordId', label: 'Record id' },
    ],
  },
  {
    kind: 'action',
    type: 'entity.update',
    label: 'Update a record',
    description: 'Patch fields on a record of the chosen entity.',
    icon: 'PencilLine',
    category: 'Actions',
    destructive: true,
    fields: [
      { key: 'entityType', label: 'Entity', type: 'entity', required: true },
      {
        key: 'recordId',
        label: 'Record',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.record.id }}',
      },
      { key: 'assignments', label: 'Set fields', type: 'assignments', required: true },
    ],
    outputs: [{ key: 'recordId', label: 'Record id' }],
  },
  {
    kind: 'action',
    type: 'omnichannel.get_contact',
    label: 'Get Contact',
    description: 'Load a contact by id into the workflow context.',
    icon: 'UserRound',
    category: 'Actions',
    module: 'omnichannel',
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
    ],
    outputs: [
      { key: 'id', label: 'Contact id' },
      { key: 'name', label: 'Name' },
      { key: 'phone', label: 'Phone' },
      { key: 'email', label: 'Email' },
      { key: 'workspaceId', label: 'Workspace id' },
      { key: 'statusId', label: 'Status id' },
      { key: 'status', label: 'Status' },
    ],
  },
  {
    kind: 'action',
    type: 'omnichannel.send_message',
    label: 'Send Message',
    description: 'Send a text or approved-template reply into a conversation.',
    icon: 'Send',
    category: 'Actions',
    module: 'omnichannel',
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      {
        key: 'mode',
        label: 'Message type',
        type: 'select',
        options: [
          { value: 'text', label: 'Text message' },
          { value: 'template', label: 'Approved template' },
        ],
      },
      {
        key: 'message',
        label: 'Message',
        type: 'textarea',
        required: true,
        mergeable: true,
        showWhen: { field: 'mode', value: 'text' },
      },
      {
        key: 'templateId',
        label: 'Template',
        type: 'whatsappTemplate',
        required: true,
        showWhen: { field: 'mode', value: 'template' },
      },
      {
        key: 'templateVariables',
        label: 'Template variables',
        type: 'templateParams',
        showWhen: { field: 'mode', value: 'template' },
      },
    ],
    outputs: [
      { key: 'messageId', label: 'Message id' },
      { key: 'status', label: 'Send status' },
    ],
  },
  // ---- plan 31 (omnichannel workflow parity) - simple steps ----
  {
    kind: 'action',
    type: 'omnichannel.assign_conversation',
    label: 'Assign conversation',
    description: 'Assign, round-robin, or unassign a conversation.',
    icon: 'UserRoundCog',
    category: 'Actions',
    module: 'omnichannel',
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace', required: true },
      {
        key: 'mode',
        label: 'Assign mode',
        type: 'select',
        required: true,
        options: [
          { value: 'user', label: 'Specific user' },
          { value: 'round_robin', label: 'Round robin' },
          { value: 'unassign', label: 'Unassign' },
        ],
      },
      {
        key: 'userId',
        label: 'User',
        type: 'omnichannelMember',
        required: true,
        showWhen: { field: 'mode', value: 'user' },
      },
    ],
    outputs: [
      { key: 'assignedUserId', label: 'Assigned user id' },
      { key: 'assigned', label: 'Assigned' },
    ],
  },
  {
    kind: 'action',
    type: 'omnichannel.add_tag',
    label: 'Add tag',
    description: 'Add a tag to a contact.',
    icon: 'Tag',
    category: 'Actions',
    module: 'omnichannel',
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace', required: true },
      { key: 'tagId', label: 'Tag', type: 'omnichannelTag', required: true },
    ],
    outputs: [
      { key: 'tags', label: 'Tags' },
      { key: 'changed', label: 'Changed' },
    ],
  },
  {
    kind: 'action',
    type: 'omnichannel.remove_tag',
    label: 'Remove tag',
    description: 'Remove a tag from a contact.',
    icon: 'Tag',
    category: 'Actions',
    module: 'omnichannel',
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace', required: true },
      { key: 'tagId', label: 'Tag', type: 'omnichannelTag', required: true },
    ],
    outputs: [
      { key: 'tags', label: 'Tags' },
      { key: 'changed', label: 'Changed' },
    ],
  },
  {
    kind: 'action',
    type: 'omnichannel.update_field',
    label: 'Update contact field',
    description: 'Set or clear a registered custom field on a contact.',
    icon: 'PencilLine',
    category: 'Actions',
    module: 'omnichannel',
    destructive: true,
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace', required: true },
      { key: 'fieldKey', label: 'Field', type: 'omnichannelContactField', required: true },
      { key: 'value', label: 'Value', type: 'text', mergeable: true },
      { key: 'clear', label: 'Clear the field', type: 'boolean' },
    ],
    outputs: [
      { key: 'fieldKey', label: 'Field key' },
      { key: 'value', label: 'Value' },
    ],
  },
  {
    kind: 'action',
    type: 'omnichannel.update_lifecycle',
    label: 'Update lifecycle',
    description: 'Move a contact to a lifecycle stage through its state machine.',
    icon: 'Activity',
    category: 'Actions',
    module: 'omnichannel',
    destructive: true,
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace', required: true },
      { key: 'toStageId', label: 'Move to stage', type: 'omnichannelLifecycleStage', required: true },
    ],
    outputs: [
      { key: 'fromStageId', label: 'From stage id' },
      { key: 'toStageId', label: 'To stage id' },
      { key: 'stageLabel', label: 'Stage label' },
    ],
  },
  {
    kind: 'action',
    type: 'omnichannel.open_conversation',
    label: 'Open conversation',
    description: 'Reopen a closed or snoozed conversation.',
    icon: 'FolderOpen',
    category: 'Actions',
    module: 'omnichannel',
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
    ],
    outputs: [
      { key: 'status', label: 'Status' },
      { key: 'changed', label: 'Changed' },
    ],
  },
  {
    kind: 'action',
    type: 'omnichannel.close_conversation',
    label: 'Close conversation',
    description: 'Close a conversation with a reason and an optional note.',
    icon: 'FolderX',
    category: 'Actions',
    module: 'omnichannel',
    destructive: true,
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      { key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace', required: true },
      { key: 'closeReasonId', label: 'Close reason', type: 'omnichannelCloseReason', required: true },
      { key: 'note', label: 'Note', type: 'textarea', mergeable: true },
    ],
    outputs: [
      { key: 'status', label: 'Status' },
      { key: 'closeReasonId', label: 'Close reason id' },
    ],
  },
  {
    kind: 'action',
    type: 'omnichannel.add_comment',
    label: 'Add comment',
    description: 'Write an internal note on the conversation (not sent to the contact).',
    icon: 'MessageSquareText',
    category: 'Actions',
    module: 'omnichannel',
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      { key: 'body', label: 'Comment', type: 'textarea', required: true, mergeable: true },
    ],
    outputs: [{ key: 'messageId', label: 'Message id' }],
  },
  {
    kind: 'action',
    type: 'omnichannel.ask_question',
    label: 'Ask a question',
    description: 'Send a message and wait for the contact to answer.',
    icon: 'HelpCircle',
    category: 'Actions',
    module: 'omnichannel',
    ports: ['answer', 'timeout'],
    fields: [
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      {
        key: 'mode',
        label: 'Message type',
        type: 'select',
        options: [
          { value: 'text', label: 'Text message' },
          { value: 'template', label: 'Approved template' },
        ],
      },
      {
        key: 'message',
        label: 'Message',
        type: 'textarea',
        required: true,
        mergeable: true,
        showWhen: { field: 'mode', value: 'text' },
      },
      {
        key: 'templateId',
        label: 'Template',
        type: 'whatsappTemplate',
        required: true,
        showWhen: { field: 'mode', value: 'template' },
      },
      {
        key: 'templateVariables',
        label: 'Template variables',
        type: 'templateParams',
        showWhen: { field: 'mode', value: 'template' },
      },
      {
        key: 'answerType',
        label: 'Answer type',
        type: 'select',
        required: true,
        options: [
          { value: 'text', label: 'Text' },
          { value: 'choice', label: 'Choice' },
          { value: 'number', label: 'Number' },
          { value: 'email', label: 'Email' },
          { value: 'phone', label: 'Phone' },
        ],
      },
      {
        key: 'choices',
        label: 'Choices',
        type: 'choiceList',
        required: true,
        showWhen: { field: 'answerType', value: 'choice' },
      },
      {
        key: 'retryLimit',
        label: 'Retry limit',
        type: 'select',
        options: [
          { value: '0', label: '0' },
          { value: '1', label: '1' },
          { value: '2', label: '2' },
          { value: '3', label: '3' },
        ],
      },
      { key: 'retryMessage', label: 'Re-ask message', type: 'textarea', mergeable: true },
      { key: 'timeoutValue', label: 'Timeout', type: 'text', required: true },
      {
        key: 'timeoutUnit',
        label: 'Timeout unit',
        type: 'select',
        required: true,
        options: [
          { value: 'minutes', label: 'Minutes' },
          { value: 'hours', label: 'Hours' },
          { value: 'days', label: 'Days' },
        ],
      },
    ],
    outputs: [
      { key: 'answer', label: 'Answer' },
      { key: 'answerRaw', label: 'Answer (raw message)' },
      { key: 'answerKey', label: 'Answer key' },
      { key: 'timedOut', label: 'Timed out' },
      { key: 'reason', label: 'Reason' },
    ],
  },
  {
    kind: 'action',
    type: 'omnichannel.wait',
    label: 'Wait',
    description: 'Pause the run for a fixed duration before continuing.',
    icon: 'Clock',
    category: 'Logic',
    module: 'omnichannel',
    fields: [
      { key: 'waitValue', label: 'Duration', type: 'text', required: true },
      {
        key: 'waitUnit',
        label: 'Duration unit',
        type: 'select',
        required: true,
        options: [
          { value: 'minutes', label: 'Minutes' },
          { value: 'hours', label: 'Hours' },
          { value: 'days', label: 'Days' },
        ],
      },
    ],
    outputs: [{ key: 'resumedAt', label: 'Resumed at' }],
  },
  {
    kind: 'action',
    type: 'omnichannel.business_hours',
    label: 'Business hours',
    description: "Branch the flow by whether a workspace is inside its business hours.",
    icon: 'Clock3',
    category: 'Logic',
    module: 'omnichannel',
    ports: ['inside', 'outside'],
    fields: [{ key: 'workspaceId', label: 'Workspace', type: 'omnichannelWorkspace', required: true }],
    outputs: [
      { key: 'isOpen', label: 'Is open' },
      { key: 'checkedAt', label: 'Checked at' },
      { key: 'timezone', label: 'Timezone' },
    ],
  },
  {
    kind: 'action',
    type: 'workflow.trigger',
    label: 'Trigger another workflow',
    description: 'Start another published workflow for this contact.',
    icon: 'Workflow',
    category: 'Actions',
    fields: [
      { key: 'workflowId', label: 'Workflow', type: 'workflowRef', required: true },
      {
        key: 'contactId',
        label: 'Contact',
        type: 'text',
        mergeable: true,
        placeholder: '{{ trigger.contact.id }}',
      },
      { key: 'payload', label: 'Payload (JSON)', type: 'textarea', mergeable: true },
    ],
    outputs: [
      { key: 'runId', label: 'Run id' },
      { key: 'workflowId', label: 'Workflow id' },
    ],
  },
  {
    kind: 'action',
    type: 'http.request',
    label: 'HTTP request',
    description: 'Call an external HTTPS endpoint and capture the response.',
    icon: 'Globe',
    category: 'Actions',
    permission: 'workflows.http',
    fields: [
      {
        key: 'method',
        label: 'Method',
        type: 'select',
        required: true,
        options: [
          { value: 'GET', label: 'GET' },
          { value: 'POST', label: 'POST' },
          { value: 'PUT', label: 'PUT' },
          { value: 'PATCH', label: 'PATCH' },
          { value: 'DELETE', label: 'DELETE' },
        ],
      },
      { key: 'url', label: 'URL', type: 'text', required: true, mergeable: true, placeholder: 'https://…' },
      { key: 'headers', label: 'Headers', type: 'keyValue' },
      {
        key: 'bodyMode',
        label: 'Body',
        type: 'select',
        options: [
          { value: 'none', label: 'No body' },
          { value: 'json', label: 'JSON' },
          { value: 'text', label: 'Text' },
        ],
      },
      {
        key: 'body',
        label: 'Body content',
        type: 'textarea',
        mergeable: true,
        showWhen: { field: 'bodyMode', value: ['json', 'text'] },
      },
      {
        key: 'timeoutSeconds',
        label: 'Timeout (seconds)',
        type: 'select',
        options: [
          { value: '5', label: '5' },
          { value: '10', label: '10' },
          { value: '20', label: '20' },
          { value: '30', label: '30' },
        ],
      },
    ],
    outputs: [
      { key: 'statusCode', label: 'Status code' },
      { key: 'ok', label: 'Ok' },
      { key: 'body', label: 'Body' },
      { key: 'json', label: 'JSON (dotted path)' },
      { key: 'durationMs', label: 'Duration (ms)' },
    ],
  },
  {
    kind: 'action',
    type: 'ai_agent.run',
    label: 'AI Agent',
    description: 'Send content to an AI agent and capture structured output.',
    icon: 'Sparkles',
    category: 'Actions',
    fields: [
      { key: 'agentId', label: 'Agent', type: 'aiAgent', required: true },
      {
        key: 'instructions',
        label: 'Instructions',
        type: 'textarea',
        required: true,
        mergeable: true,
      },
      {
        key: 'inputText',
        label: 'Message',
        type: 'textarea',
        required: true,
        mergeable: true,
        placeholder: '{{ trigger.message.text }}',
      },
      { key: 'outputParams', label: 'Output parameters', type: 'outputSchema', required: true },
      { key: 'clarificationOutputKey', label: 'Clarification output', type: 'clarificationOutput' },
    ],
    // Dynamic - the drawer lists config.outputParams as nodes.<id>.<key>.
    outputs: [],
  },
  {
    kind: 'action',
    type: 'ai_agent.clear_state',
    label: 'Clear Agent State',
    description: 'Clear retained values from an earlier AI Agent.',
    icon: 'Eraser',
    category: 'Actions',
    fields: [
      { key: 'agentNodeId', label: 'Agent', type: 'agentNode', required: true },
    ],
    outputs: [
      { key: 'cleared', label: 'Cleared' },
      { key: 'previousRevision', label: 'Previous revision' },
    ],
  },
  {
    kind: 'action',
    type: 'ai_agent.read_state',
    label: 'Read Agent State',
    // Identifies WHAT it is, not how to use it (foolproof-UI).
    description: 'Read the current saved values from an earlier AI Agent.',
    icon: 'BookOpen',
    category: 'Actions',
    fields: [
      { key: 'agentNodeId', label: 'Agent', type: 'agentNode', required: true },
    ],
    // Outputs are DYNAMIC: the drawer lists the selected agent's stateful
    // fields as nodes.<id>.<field> plus the reserved stateRevision /
    // pendingField / exists diagnostics (see readStateOutputParams).
    outputs: [],
  },
  {
    kind: 'action',
    type: 'redis.command',
    label: 'Redis',
    description: 'Read or mutate a value in the workflow data store.',
    icon: 'Database',
    category: 'Actions',
    destructiveWhen: { field: 'operation', values: ['set', 'delete', 'increment', 'list_push', 'list_pop'] },
    fields: [
      {
        key: 'operation',
        label: 'Operation',
        type: 'select',
        options: [
          { value: 'get', label: 'Get' },
          { value: 'set', label: 'Set' },
          { value: 'delete', label: 'Delete' },
          { value: 'increment', label: 'Increment' },
          { value: 'list_push', label: 'List Push' },
          { value: 'list_pop', label: 'List Pop' },
          { value: 'list_length', label: 'List Length' },
        ],
      },
      { key: 'key', label: 'Key', type: 'text', required: true, mergeable: true },
      { key: 'value', label: 'Value', type: 'text', required: true, mergeable: true, showWhen: { field: 'operation', value: 'set' } },
      { key: 'amount', label: 'Amount', type: 'text', required: true, mergeable: true, showWhen: { field: 'operation', value: 'increment' } },
      { key: 'value', label: 'Value', type: 'text', required: true, mergeable: true, showWhen: { field: 'operation', value: 'list_push' } },
      {
        key: 'end',
        label: 'List end',
        type: 'select',
        options: [{ value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }],
        showWhen: { field: 'operation', value: 'list_push' },
      },
      {
        key: 'end',
        label: 'List end',
        type: 'select',
        options: [{ value: 'left', label: 'Left' }, { value: 'right', label: 'Right' }],
        showWhen: { field: 'operation', value: 'list_pop' },
      },
      { key: 'ttlSeconds', label: 'TTL seconds', type: 'text', mergeable: true, showWhen: { field: 'operation', value: 'set' } },
    ],
    outputs: [{ key: 'value', label: 'Value' }, { key: 'deleted', label: 'Deleted' }, { key: 'length', label: 'Length' }],
  },
  {
    kind: 'action',
    type: 'code.run',
    label: 'Code',
    description: 'Transform mapped values with restricted Python.',
    icon: 'Code2',
    category: 'Actions',
    permission: 'workflows.code',
    fields: [
      { key: 'language', label: 'Language', type: 'select', options: [{ value: 'python', label: 'Python' }], required: true },
      { key: 'source', label: 'Python', type: 'code', required: true },
      { key: 'inputs', label: 'Input mappings', type: 'codeInputs' },
      { key: 'outputs', label: 'Output parameters', type: 'outputSchema', required: true },
      { key: 'capabilities', label: 'Runtime capabilities', type: 'codeCapabilities' },
    ],
    outputs: [],
  },
];

/** The IF node (built-in - D8). One catalog row so the palette/createNode/node
 * card treat it uniformly; its config (the rule tree) renders specially. */
export const IF_CATALOG: IfCatalogEntry[] = [
  {
    kind: 'if',
    type: 'if',
    label: 'Condition',
    description: 'Branch the flow - matching runs take the true path.',
    icon: 'GitBranch',
    category: 'Logic',
    fields: [],
    outputs: [],
  },
];

const CATALOG: NodeCatalogEntry[] = [...TRIGGER_CATALOG, ...ACTION_CATALOG, ...IF_CATALOG];

export function catalogEntry(type: string): NodeCatalogEntry | undefined {
  return CATALOG.find((e) => e.type === type);
}

export function isTriggerType(type: string): boolean {
  return TRIGGER_CATALOG.some((e) => e.type === type);
}
